on: workflow_dispatch

name: Build and Publish

jobs:
    test:
        name: 'node ${{ matrix.node }} ${{ matrix.os }} '
        runs-on: '${{ matrix.os }}'
        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [14, 12, 10]
        steps:
            - uses: actions/setup-node@v2.1.1
              with:
                  node-version: ${{ matrix.node }}
            - uses: actions/checkout@v1
            - run: yarn install
            - run: yarn lint
            - run: yarn test
    release:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - uses: actions/setup-node@v2.1.1
              with:
                  node-version: 12
            - uses: actions/checkout@v1
            - run: yarn install
            - run: yarn build
            - run: npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
